razorpay.key.id=rzp_test_TL1nEjh4MukNqm
razorpay.key.secret=rwTVt2WvgLhQIc1K0nFrAp06
spring.application.name=backend

spring.data.mongodb.uri=mongodb://localhost:27017/foodexpress_db

server.port=8080

razorpay.key.id=rzp_test_TM3bHhkJ2OC285
razorpay.key.secret=jwiDRz0U8xbAmDWtjD5t4B31

spring.application.name=backend

spring.data.mongodb.uri=mongodb://localhost:27017/foodexpress_db

server.port=8080

# ==========================
# Email Configuration
# ==========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pradotpatil7777@gmail.com
spring.mail.password=cpag iekt fxim qamd


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true