

spring.application.name=backend
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}

razorpay.key.id=${rzp_test_TL1nEjh4MukNqm}
razorpay.key.secret=${rwTVt2WvgLhQIc1K0nFrAp06}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${pradotpatil7777@gmail.com}
spring.mail.password=${cpag iekt fxim qamd}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

